### ISSUE TITLE
refactor: rename identifier to calibre-web

### ISSUE THREAD

**Issue by moan0s** [lingawakad/ansible-role-calibre-web#1]
In [the defaults](https://github.com/lingawakad/ansible-role-calibre-web/blob/d58d4562a2601822505509bc709c932146d4a0e2/defaults/main.yml#L7C1-L7C23) the identifier is set to `calibre_web`. Other roles of the mash-playbook make use of a `-` to connect a name. I'd therefore suggest renaming the identifier to `calibre-web` as people expect this naming schema for things like `journalctl -fu mash-XX`.

The same goes for
* the systemd service file
* the [tags of tasks](https://github.com/lingawakad/ansible-role-calibre-web/blob/master/tasks/main.yml)

**Comment by lingawakad** [comment]
thanks for the check! i think everything that needed to got changed...

**Comment by lingawakad** [comment]
thanks for the check! i think everything that needed to got changed...
