### ISSUE TITLE
 Admin login broken; Password reset doesn't have an effect.

### ISSUE THREAD

**Issue by moan0s** [lingawakad/ansible-role-calibre-web#2]
It seems that I encounter the bug described [in the calibre-web project](https://github.com/janeczku/calibre-web/issues/2853) but the offered solutions don't work for me. This is happening on the new `v0.6.21-1` tag and at some point I was running this role successfully before.

**Comment by lingawakad** [comment]
hey @moan0s i can't reproduce this issue. i did remove a tmpfs volume from the systemd unit, since it was trying to install the mod there, not in the container... database should be in the data volume, tho...
did you add the docker_mod variable, or just update the tag and run the playbook?

**Comment by moan0s** [comment]
I did just update the tag and run the playbook so it's very possible these things are unrelated.

**Comment by moan0s** [comment]
After a reinstall, everything works. So whatever it was, it doesn't seem that the update was the issue. Closing.
